name: Manual push

on:      
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to push on docker hub'
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${{ github.event.inputs.tag }}

      - name: Publish docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wirepas/${{ github.event.repository.name }}
          tags: ${{ steps.get_tag_name.outputs.TAG_NAME }}
